export interface Perfume {
  id: string
  name: string
  brand: string
  price: number
  image: string
  gender: "male" | "female" | "unisex"
  volume: string
  rating: number
  description: string
  featured?: boolean
}

export const perfumes: Perfume[] = [
  {
    id: "1",
    name: "N°5",
    brand: "Chanel",
    price: 12500,
    image: "/chanel-no-5-perfume-bottle-elegant.jpg",
    gender: "female",
    volume: "100мл",
    rating: 5,
    description: "Вечная классика, олицетворяющая элегантность",
    featured: true,
  },
  {
    id: "2",
    name: "Sauvage",
    brand: "Dior",
    price: 9800,
    image: "/dior-sauvage-perfume-bottle-masculine.jpg",
    gender: "male",
    volume: "100мл",
    rating: 5,
    description: "Дикий и благородный, грубый и утончённый",
    featured: true,
  },
  {
    id: "3",
    name: "Black Opium",
    brand: "Yves Saint Laurent",
    price: 8900,
    image: "/ysl-black-opium-perfume-bottle-dark.jpg",
    gender: "female",
    volume: "50мл",
    rating: 4,
    description: "Пленительный и таинственный кофейно-цветочный аромат",
    featured: true,
  },
  {
    id: "4",
    name: "Bleu de Chanel",
    brand: "Chanel",
    price: 11200,
    image: "/bleu-de-chanel-perfume-bottle-blue.jpg",
    gender: "male",
    volume: "100мл",
    rating: 5,
    description: "Древесно-ароматический аромат для мужчин",
    featured: true,
  },
  {
    id: "5",
    name: "Guilty",
    brand: "Gucci",
    price: 7500,
    image: "/gucci-guilty-perfume-bottle-gold.jpg",
    gender: "unisex",
    volume: "50мл",
    rating: 4,
    description: "Дерзкий и смелый, для свободных духом",
    featured: true,
  },
  {
    id: "6",
    name: "La Vie Est Belle",
    brand: "Lancôme",
    price: 8200,
    image: "/lancome-la-vie-est-belle-perfume-bottle-pink.jpg",
    gender: "female",
    volume: "75мл",
    rating: 5,
    description: "Жизнь прекрасна — сладкий гурманский аромат",
    featured: true,
  },
  {
    id: "7",
    name: "Acqua di Gio",
    brand: "Giorgio Armani",
    price: 7800,
    image: "/acqua-di-gio-armani-perfume-bottle.jpg",
    gender: "male",
    volume: "100мл",
    rating: 4,
    description: "Свежие морские ноты для современного мужчины",
  },
  {
    id: "8",
    name: "Miss Dior",
    brand: "Dior",
    price: 9500,
    image: "/miss-dior-perfume-bottle-floral.jpg",
    gender: "female",
    volume: "100мл",
    rating: 5,
    description: "Любовное послание во флаконе",
  },
  {
    id: "9",
    name: "Oud Wood",
    brand: "Tom Ford",
    price: 21000,
    image: "/tom-ford-oud-wood-perfume-bottle-luxury.jpg",
    gender: "unisex",
    volume: "50мл",
    rating: 5,
    description: "Экзотический, дымный, чувственный уд",
  },
  {
    id: "10",
    name: "Light Blue",
    brand: "Dolce & Gabbana",
    price: 6500,
    image: "/dolce-gabbana-light-blue-perfume-bottle.jpg",
    gender: "female",
    volume: "100мл",
    rating: 4,
    description: "Средиземноморское лето во флаконе",
  },
  {
    id: "11",
    name: "Aventus",
    brand: "Creed",
    price: 35000,
    image: "/creed-aventus-perfume-bottle-luxury.jpg",
    gender: "male",
    volume: "100мл",
    rating: 5,
    description: "Король ароматов",
  },
  {
    id: "12",
    name: "Good Girl",
    brand: "Carolina Herrera",
    price: 8900,
    image: "/carolina-herrera-good-girl-perfume-bottle-heel.jpg",
    gender: "female",
    volume: "80мл",
    rating: 4,
    description: "Двойственность современной женщины",
  },
  {
    id: "13",
    name: "Invictus",
    brand: "Paco Rabanne",
    price: 6800,
    image: "/paco-rabanne-invictus-perfume-bottle-trophy.jpg",
    gender: "male",
    volume: "100мл",
    rating: 4,
    description: "Для победителя в каждом из нас",
  },
  {
    id: "14",
    name: "Coco Mademoiselle",
    brand: "Chanel",
    price: 13500,
    image: "/chanel-coco-mademoiselle-perfume-bottle.jpg",
    gender: "female",
    volume: "100мл",
    rating: 5,
    description: "Свежий и чувственный восточный аромат",
  },
  {
    id: "15",
    name: "Tobacco Vanille",
    brand: "Tom Ford",
    price: 24000,
    image: "/tom-ford-tobacco-vanille-perfume-bottle.jpg",
    gender: "unisex",
    volume: "50мл",
    rating: 5,
    description: "Роскошная тёплая пряная ваниль",
  },
  {
    id: "16",
    name: "J'adore",
    brand: "Dior",
    price: 10500,
    image: "/placeholder.svg?height=400&width=300",
    gender: "female",
    volume: "100мл",
    rating: 5,
    description: "Абсолютная женственность",
  },
  {
    id: "17",
    name: "Versace Eros",
    brand: "Versace",
    price: 7200,
    image: "/placeholder.svg?height=400&width=300",
    gender: "male",
    volume: "100мл",
    rating: 4,
    description: "Греческий бог любви и страсти",
  },
  {
    id: "18",
    name: "Flowerbomb",
    brand: "Viktor & Rolf",
    price: 9200,
    image: "/placeholder.svg?height=400&width=300",
    gender: "female",
    volume: "100мл",
    rating: 4,
    description: "Взрывной цветочный букет",
  },
  {
    id: "19",
    name: "CK One",
    brand: "Calvin Klein",
    price: 4500,
    image: "/placeholder.svg?height=400&width=300",
    gender: "unisex",
    volume: "100мл",
    rating: 3,
    description: "Оригинальный унисекс-аромат",
  },
  {
    id: "20",
    name: "Baccarat Rouge 540",
    brand: "Maison Francis Kurkdjian",
    price: 42000,
    image: "/placeholder.svg?height=400&width=300",
    gender: "unisex",
    volume: "70мл",
    rating: 5,
    description: "Кристальный и сияющий шедевр",
  },
  {
    id: "21",
    name: "Le Male",
    brand: "Jean Paul Gaultier",
    price: 6900,
    image: "/placeholder.svg?height=400&width=300",
    gender: "male",
    volume: "125мл",
    rating: 4,
    description: "Легендарный мужской аромат",
  },
  {
    id: "22",
    name: "Chance",
    brand: "Chanel",
    price: 11800,
    image: "/placeholder.svg?height=400&width=300",
    gender: "female",
    volume: "100мл",
    rating: 4,
    description: "Неожиданная цветочная эссенция",
  },
  {
    id: "23",
    name: "Spicebomb",
    brand: "Viktor & Rolf",
    price: 8500,
    image: "/placeholder.svg?height=400&width=300",
    gender: "male",
    volume: "90мл",
    rating: 4,
    description: "Взрывное пряное тепло",
  },
  {
    id: "24",
    name: "Mon Paris",
    brand: "Yves Saint Laurent",
    price: 8700,
    image: "/placeholder.svg?height=400&width=300",
    gender: "female",
    volume: "90мл",
    rating: 4,
    description: "Интенсивный фруктовый шипр",
  },
]

export const brands = [...new Set(perfumes.map((p) => p.brand))].sort()
export const volumes = ["30мл", "50мл", "75мл", "100мл+"]
